config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "/auth/facebook", as: :sign_in_with_facebook
  get "/auth/facebook/callback" => "callbacks#facebook"
  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/google_oauth2/callback" => "callbacks#google_oauth2"
  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"
  scope module: 'users' do
    resources :account_verifications, only: [:new, :create, :edit]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  root "home#home", as: :home
  get "/home" => "home#home"
  get "/about" => "home#about", as: :about_us

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :delete]
  resources :posts do

    resources :favourites, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :destroy, :update]
  end

  resources :favourites, only: [:index]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
  # has_many :favourites, dependent: :destroy
  # has_many :faved_posts, through: :favourites, source: :post

    validates(:body, {presence: true, uniqueness: {message: "must be unique per blog post!"}})

    def user_full_name
        user ? user.full_name : ""
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_post
    before_action :find_and_authorize_comment, only: :destroy

    def create
        @post             = Post.find params[:post_id]
        comment_params    = params.require(:comment).permit(:body)
        @comment          = Comment.new comment_params
        @comment.post     = @post
        @comment.user     = current_user
        respond_to do |format|
            if @comment.save
                # redirect_to post_path(@post), notice: "Thanks for answering"
                format.html { redirect_to post_path(@post), notice: "Thanks for commenting" }
                format.js { render :create_success }
            else
                flash[:alert]   = "Not saved"
                # render "/posts/show"
                format.html { render "/posts/show" }
                format.js { render :create_failure }
            end
        end
    end

    def destroy
        @comment.destroy
        respond_to do |format|
            format.html { redirect_to post_path(@post), notice: "Comment deleted!" }
            format.js { render }
        end
    end

    def show
        @comment = Comment.find params[:id]
    end

    def edit
        @comment = Comment.find params[:id]
    end

    def update
        @comment = Comment.find params[:id]
        comment_params = params.require(:comment).permit([:body])
        respond_to do |format|
            if @comment.update comment_params
                format.html { redirect_to comment_path(@comment), notice: "Thanks for commenting" }
                format.js { render :update_success }
            else
                format.html { render "/comments/edit" }
                format.js { render :update_failure }
            end
        end
    end

  private

    def find_post
        @post = Post.find params[:post_id]
    end

    def find_and_authorize_comment
    # head will stop the HTTP request and send a response code depending on the
    # symbole (first argument) that you pass in.
    # head :unauthorized unless can? :destroy, @answer
        @comment = @post.comments.find params[:id]
        redirect_to home_path unless can? :destroy, @comment
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>" style="<%= style if defined?(style) %>">
    <%= comment.body %>
    by: <%= comment.user_full_name.titleize %>
    <% if can? :destroy, comment %>
        <%= link_to "delete", post_comment_path(@post, comment),
                              remote: true,
                              data: {confirm: "Are you sure?"},
                              method: :delete,
                              class: "btn btn-primary btn-sm" %>
    <% end %>
    <% if can? :edit, comment %>
        <%= link_to "Edit", edit_post_comment_path(@post, comment),
                            remote: true,
                            data: {toggle: "modal", target: "#edit-comment"},
                            class: "btn btn-primary btn-sm" %>
    <% end %>
    <hr>
</div>

app/views/comments/_comments.html.erb
<% comments.order("created_at desc").each do |ans| %>
    <%= render "/comments/comment", comment: ans %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for [@post, comment], remote: true do |f|  %>
    <%= f.input :body, label: false %>
    <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary" %>
<% end %>

app/views/comments/_modal_form.html.erb
<%= simple_form_for [@post, @comment], remote: true do |f|  %>
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Edit Comment</h4>
        </div>
        <div class="modal-body">
            <%= f.input :body, label: false, placeholder: "Something...", input_html: { rows: 5 } %>
            <div>
                <%= @comment.errors.full_messages.join(", ") %>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary"%>
        </div>
    </div>
</div>
<% end %>

app/views/comments/create_failure.js.erb
$("#comment-form").html("<%= j render '/comments/form', comment: @comment %>");

app/views/comments/create_success.js.erb
$("#comments").prepend("<%= j render '/comments/comment', comment: @comment, style: 'display: none' %>");
$("#comment-form").html("<%= j render '/comments/form', comment: Comment.new %>");
$("#<%= dom_id(@comment) %>").fadeIn(1000);

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(1000, function(){
  $(this).remove();
});

app/views/comments/edit.js.erb
$("#edit-comment").html("<%= j render 'modal_form' %>");

app/views/comments/update_failure.js.erb
$("#edit-comment").html("<%= j render '/comments/modal_form', comment: @comment %>");

app/views/comments/update_success.js.erb
$("#comments").html("<%= j render 'comments', comments: @post.comments %>");
$('#edit-comment').modal('hide')