config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "/auth/facebook", as: :sign_in_with_facebook
  get "/auth/facebook/callback" => "callbacks#facebook"
  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/google_oauth2/callback" => "callbacks#google_oauth2"
  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"
  scope module: 'users' do
    resources :account_verifications, only: [:new, :create, :edit]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  root "home#home", as: :home
  get "/home" => "home#home"
  get "/about" => "home#about", as: :about_us

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :delete]
  resources :posts do

    resources :favourites, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :destroy, :update]
  end

  resources :favourites, only: [:index]

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :category
    belongs_to :user

    has_many :comments, dependent: :nullify
    has_many :favourites, dependent: :destroy
    has_many :users, through: :favourites
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    validates(:title, {presence: true, uniqueness: {message: "must be unique!"}})

    mount_uploader :image, ImageUploader

    def self.search(search)
        where("title ILIKE ? OR body ILIKE ?", "%#{search}%", "%#{search}%")
    end

    def user_full_name
        user ? user.full_name : ""
    end

    def favourite_for(user)
        favourites.find_by_user_id user if user
    end

end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController

  def index
    @posts = Post.order(:created_at)
    render json: @posts
  end

  def show
    post = Post.find params[:id]
    render json: post
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_post, only: [:show, :edit, :update, :destroy]

    def new
        @post = Post.new
    end

    def index
        @posts = Post.all
        if params[:search]
            @posts = @posts.search(params[:search]).order("created_at DESC")
        else
            @posts = @posts.order('created_at DESC')
        end
        @posts = @posts.page(params[:page]).per(10)
    end

    def create
    @post = Post.new post_params
    @post.user = current_user
        if @post.save
            redirect_to post_path(@post), notice: "Post created!"
        else
            flash[:alert] = "Post didn't save!"
            render :new
        end
    end

    def show
        @comment  = Comment.new
        respond_to do |format|
            format.html { render }
            format.json { render json: @post.to_json }
            format.xml  { render xml: @post.to_xml }
        end
    end

    def edit
    end

    def update
        @post = Post.find params[:id]
        post_params = params.require(:post).permit([:title, :body])
        if @post.update post_params
            redirect_to post_path(@post)
        else
            render :edit
        end
    end

    def destroy
        @post.destroy
        redirect_to posts_path
    end

    private

    def find_post
        @post = Post.find params[:id]
    end

    def find_owner_post
        @post = current_user.posts.find params[:id]
    end

    def post_params
        params.require(:post).permit([:title, :body, :image, :category_id, {tag_ids: []}])
    end

    def user_favourite
        @user_favourite ||= @post.favourite_for(current_user)
    end
    helper_method :user_favourite

end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
    <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= simple_form_for @post do |f| %>
    <%= f.input :title %>
    <%= f.input :body, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
    <%= f.association :category %>
    <%= f.association :tags, input_html: {class: "chosen-select"} %>
    <%= f.input :image %>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
    <h1>Editing post</h1>
    <%= render "form" %>
</div>

app/views/posts/index.html.erb
<div class="container">
    <h1>All Posts</h1>
    <%= form_tag(posts_path, :method => 'get', id: "search-form") do %>
        <p>
            <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
            <%= submit_tag "Search" %>
        </p>
    <% end %>
    <br>
    <% @posts.each do |post| %>
    <div>
        <%= link_to post.title, post_path(post) %>
    </div>
    <% end %>
    <hr>
    <%= paginate @posts %>
    <%= page_entries_info @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">
    <h1>Creating new post</h1>
    <%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="container">
    <nav>
        <div class="col s12">
            <a <%= link_to "Home", home_path %></a>
            >
            <a <%= link_to "All Posts", posts_path %></a>
        </div>
    </nav>
    <h1><%= @post.title %></h1>
    <p><%= @post.body.html_safe %></p>
    <p><%= @post.created_at %></p>
    <p>Created By: <%= @post.user_full_name.titleize %></p>
    <p>Tags: <%= @post.tags.map{|t| t.name }.join(", ") %></p>
    <% if @post.image.present? %>
        <%= image_tag @post.image.url, class: "full-width" %>
    <% end %>
    <% if can? :edit, @post %>
        <%= link_to "Edit", edit_post_path(@post) %>
    <% end %>
    <% if can? :destroy, @post %>
        <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure"} %>
    <% end %>
    <% if user_favourite %>
        <%= link_to "Un-Fave", post_favourite_path(@post, user_favourite), method: :delete %>
        <% else %>
        <%= link_to "Favourite", post_favourites_path(@post), method: :post %>
    <% end %>
    <div id="comment-form">
        <%= render "/comments/form", comment: @comment %>
    </div>
    <h2>Comments</h2>
    <div id="comments">
        <%= render "/comments/comments", comments: @post.comments %>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="edit-comment" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
</div>
<%= render "/layouts/analytics" if Rails.env.production? %>