config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  get "/auth/facebook", as: :sign_in_with_facebook
  get "/auth/facebook/callback" => "callbacks#facebook"
  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/google_oauth2/callback" => "callbacks#google_oauth2"
  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/twitter/callback" => "callbacks#twitter"
  scope module: 'users' do
    resources :account_verifications, only: [:new, :create, :edit]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  root "home#home", as: :home
  get "/home" => "home#home"
  get "/about" => "home#about", as: :about_us

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :users, only: [:new, :create, :edit, :update, :delete]
  resources :posts do

    resources :favourites, only: [:create, :destroy]
    resources :comments, only: [:create, :edit, :destroy, :update]
  end

  resources :favourites, only: [:index]

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80175501-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
    <div class="container">
        <div class="navbar-text pull-left">
            <p>© 2016 BigShark Design Studios</p>
        </div>
        <div class="navbar-text pull-right">
            <a href="https://ca.linkedin.com/in/lextang"><i class="fa fa-linkedin fa-2x"></i></a>
            <a href="https://github.com/a-tang"><i class="fa fa-github fa-2x"></i></a>
        </div>
    </div>
</div>

app/views/layouts/_top_navbar.html.erb
  <!-- bootstrap navbar -->
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <!-- <div class="navbar-header"> -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        <!-- logo and company name -->
        </button>
        <a class="navbar-left" href="<%= home_path %>">
        <span class="glyphicon glyphicon-fire logo">
        <a href="<%= home_path %>" class="navbar-left company-name">BlogAT</a>
        <!--img class="logo-image" src="images/logo.png"-->
        <div class="navbar-collapse collapse navbar-right">
            <ul class="nav navbar-nav navbar text-center">
                <!-- navigation items -->
                <li><%= link_to "Home", home_path %></li>
                <li><%= link_to "About", about_us_path %></li>
                <li><a href="<%= posts_path %>">View all posts</a></li>
                <% if user_signed_in? %>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= "#{current_user.full_name.titleize}"%><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<%= new_post_path %>">Create a post</a></li>
                        <li><a href="<%= favourites_path %>">Your favourite posts</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="<%= edit_user_path(current_user) %>">Edit profile</a></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "Log out", sessions_path, method: :delete %></li>
                    </ul>
                </li>
                <% else %>
                <!-- <li><a href="<%= new_user_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li> -->
                <li><a data-popup-open="popup-1" href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                <% end %>
            </ul>
          </a>
        </div>
    </div>
</nav>
<div class="popup" data-popup="popup-1">
    <div class="popup-inner">
        <h2><center>Sign In</center></h2>
        <div class="sign-in-modal">
            <%= link_to sign_in_with_facebook_path, id: "sign_in", class:"btn btn-block btn-social btn-facebook" do %>
                <span class="fa fa-facebook"></span>
                <span>Sign In With Facebook</span>
                <% end %>
                <%= link_to sign_in_with_twitter_path, class:"btn btn-block btn-social btn-twitter" do %>
                <span class="fa fa-twitter"></span>
                <span>Sign In With Twitter</span>
                <% end %>
                <%= link_to sign_in_with_google_path, id: "sign_in", class:"btn btn-block btn-social btn-google" do %>
                <span class="fa fa-google"></span>
                <span>Sign In With Google</span>
                <% end %>
            <br>
            <div class="form-group row_modal">
                <p><a data-popup-close="popup-1" href="#">Close</a></p>
            </div>
        </div>
        <div>
            <a class="popup-close" data-popup-close="popup-1" href="#">x</a>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>MyBlog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body data-spy="scroll" data-target=".navbar">
    <%= render 'layouts/top_navbar' %>
    <% if notice %>
    <div id="notice_wrapper">
        <div class="notice"><%= notice %></div>
    </div>
    <% elsif alert %>
    <div id="notice_wrapper">
        <div class="notice"><%= alert %></div>
    </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render "/layouts/analytics" if Rails.env.production? %>
</body>
</html>